"""empty message

Revision ID: 781b0fb2929d
Revises: 
Create Date: 2021-10-12 00:29:00.157077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '781b0fb2929d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_content', sa.Column('like', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media_content', 'like')
    # ### end Alembic commands ###
