"""empty message

Revision ID: 1953f6c6b04c
Revises: 
Create Date: 2021-10-10 16:59:50.293566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1953f6c6b04c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'google_user', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'google_user', type_='unique')
    # ### end Alembic commands ###
