"""empty message

Revision ID: 41b568031278
Revises: 4a09ddaac878
Create Date: 2021-10-04 19:50:10.649464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41b568031278'
down_revision = '4a09ddaac878'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('google_user', sa.Column('preferences', sa.String(length=30), nullable=True))
    op.add_column('google_user', sa.Column('likes_list', sa.JSON(), nullable=True))
    op.drop_index('user_name', table_name='google_user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('user_name', 'google_user', ['user_name'], unique=False)
    op.drop_column('google_user', 'likes_list')
    op.drop_column('google_user', 'preferences')
    # ### end Alembic commands ###
