"""empty message

Revision ID: 6dca0691e235
Revises: 1953f6c6b04c
Create Date: 2021-10-13 15:40:20.107340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dca0691e235'
down_revision = '1953f6c6b04c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('google_user', sa.Column('pwd', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('google_user', 'pwd')
    # ### end Alembic commands ###
