"""empty message

Revision ID: 7ae47aa32f92
Revises: e8026a56c1f4
Create Date: 2021-10-06 18:17:06.090749

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7ae47aa32f92'
down_revision = 'e8026a56c1f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media_content', 'actor')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_content', sa.Column('actor', mysql.JSON(), nullable=True))
    # ### end Alembic commands ###
