"""empty message

Revision ID: e105fec61f56
Revises: 
Create Date: 2021-10-06 09:36:06.472537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e105fec61f56'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('google_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=30), nullable=False),
    sa.Column('user_name', sa.String(length=30), nullable=False),
    sa.Column('preferences', sa.JSON(), nullable=True),
    sa.Column('likes_list', sa.JSON(), nullable=True),
    sa.Column('latest_reviews_list', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('google_user')
    # ### end Alembic commands ###
