"""empty message

Revision ID: e8026a56c1f4
Revises: e105fec61f56
Create Date: 2021-10-06 15:38:52.694300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8026a56c1f4'
down_revision = 'e105fec61f56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thumbnail', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('genre', sa.Text(), nullable=True),
    sa.Column('running_time', sa.Text(), nullable=True),
    sa.Column('actor', sa.JSON(), nullable=True),
    sa.Column('synop', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('media_content')
    # ### end Alembic commands ###
